"""08_rfi_builder — Request For Information (RFI) generation.

Identifies information gaps — open low-confidence assumptions and components that
lack supplier evidence — and renders them as a structured RFI document (Markdown)
that a human can send to suppliers or internal teams.

The RFI is the system's mechanism for *resolving* uncertainty rather than hiding
it: instead of asserting unknowns as facts, it asks for evidence.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date

from .governance import AssumptionLedger, assert_clean
from .supplier_evidence import SupplierEvidenceTable


@dataclass
class RFIItem:
    ref: str
    topic: str
    question: str
    rationale: str
    priority: str = "medium"   # low | medium | high


@dataclass
class RFI:
    title: str
    branch: str
    items: list[RFIItem] = field(default_factory=list)
    created: str = field(default_factory=lambda: date.today().isoformat())
    recipient: str = "TBD"

    def to_markdown(self) -> str:
        lines = [
            f"# Request for Information — {self.title}",
            "",
            f"- **Branch:** {self.branch}",
            f"- **Recipient:** {self.recipient}",
            f"- **Date:** {self.created}",
            f"- **Items:** {len(self.items)}",
            "",
            "> This RFI is generated by the HAEN Hypercar Design Support AI to "
            "resolve open assumptions and gather evidence. Responses are inputs "
            "to human-reviewed engineering work; no figure is treated as final "
            "until verified by a HAEN engineer.",
            "",
            "| Ref | Priority | Topic | Question | Rationale |",
            "|-----|----------|-------|----------|-----------|",
        ]
        for item in self.items:
            q = item.question.replace("|", "\\|")
            r = item.rationale.replace("|", "\\|")
            lines.append(
                f"| {item.ref} | {item.priority} | {item.topic} | {q} | {r} |"
            )
        lines.append("")
        text = "\n".join(lines)
        assert_clean(text)  # governance gate: never emit a forbidden claim
        return text


def build_rfi(
    *,
    title: str,
    branch: str,
    ledger: AssumptionLedger | None = None,
    evidence: SupplierEvidenceTable | None = None,
    expected_components: list[str] | None = None,
    recipient: str = "TBD",
) -> RFI:
    """Assemble an RFI from open assumptions and evidence gaps.

    - Each open, low-confidence assumption becomes a high-priority RFI item.
    - Each unverified evidence record becomes a medium-priority item.
    - Each expected component lacking any evidence becomes a high-priority item.
    """
    items: list[RFIItem] = []
    counter = 1

    if ledger is not None:
        for a in ledger.open_low_confidence():
            if branch not in ("all", a.branch) and a.branch != "all":
                continue
            items.append(
                RFIItem(
                    ref=f"A-{counter:03d}",
                    topic=a.key,
                    question=(
                        f"Please provide evidence for the assumption: "
                        f"'{a.statement}' (currently assumed {a.value} {a.unit}, "
                        f"source: {a.source})."
                    ),
                    rationale=f"Open assumption with {a.confidence.value} confidence.",
                    priority="high",
                )
            )
            counter += 1

    if evidence is not None:
        for r in evidence.unverified():
            if branch not in ("all", r.branch) and r.branch != "all":
                continue
            items.append(
                RFIItem(
                    ref=f"E-{counter:03d}",
                    topic=r.component,
                    question=(
                        f"Please provide verifiable documentation for "
                        f"'{r.claim}' from {r.supplier} "
                        f"(current evidence: {r.evidence_type.value}, "
                        f"ref: {r.document_ref or 'none'})."
                    ),
                    rationale=f"Evidence currently {r.verification.value}.",
                    priority="medium",
                )
            )
            counter += 1

        if expected_components:
            for comp in evidence.components_without_evidence(expected_components):
                items.append(
                    RFIItem(
                        ref=f"C-{counter:03d}",
                        topic=comp,
                        question=(
                            f"No supplier evidence exists for '{comp}'. Please "
                            f"provide a datasheet, quote or test report."
                        ),
                        rationale="Component has no evidence on file.",
                        priority="high",
                    )
                )
                counter += 1

    return RFI(title=title, branch=branch, items=items, recipient=recipient)
